version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
        - DJANGO_SETTINGS_MODULE=fragdenstaat_de.settings.development
        - DJANGO_CONFIGURATION=Dev
        - DATABASE_URL=postgres://postgres@db/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
